let recipes = [
  {
    name: "Chocolat Chaud à l'Ancienne",
    id:1,
    category: "drinks",
    favorite: false,
    persons: 2,
    comments: [],
    ingredients: [
      {
        name: "lait entier",
        quantity: 500,
        unit: "mL",
        photo: "",
      },
      {
        name: "chocolat noir (70% de cacao)",
        quantity: 100,
        unit: "g",
        photo: "",
      },
      {
        name: "sucre",
        quantity: 2,
        unit: "c. à s.",
        photo: "",
      },
      {
        name: "vanille liquide",
        quantity: 1,
        unit: "c. à c.",
        photo: "",
      },
      {
        name: "Crème fouettée",
        quantity: 1,
        unit: "",
        photo: "",
      },
    ],
    steps: [
      "Faites chauffer le lait dans une casserole à feu moyen.",
      "Ajoutez le chocolat noir cassé en morceaux, le sucre et la vanille liquide.",
      "Remuez constamment jusqu'à ce que le chocolat soit complètement fondu et que le mélange soit bien chaud.",
      "Versez dans des tasses et ajoutez une cuillère de crème fouettée si désiré.",
      "Servez immédiatement.",
    ],
    prepTiming: { duration: 5, unit: "min" },
    restTiming: { duration: 0, unit: "h" },
    cookTiming: { duration: 0, unit: "min" },
    photo:
      "https://www.delscookingtwist.com/wp-content/uploads/2021/01/Best-Homemade-Hot-Chocolate_7.jpg",
  },
  {
    name: "Smoothie aux Fruits Rouges",
    id:2,
    category: "drinks",
    favorite: false,
    persons: 2,
    comments: [],
    ingredients: [
      {
        name: "fraises",
        quantity: 150,
        unit: "g",
        photo: "",
      },
      {
        name: "framboises",
        quantity: 100,
        unit: "g",
        photo: "",
      },
      {
        name: "myrtilles",
        quantity: 100,
        unit: "g",
        photo: "",
      },
      {
        name: "banane",
        quantity: 1,
        unit: "",
        photo: "",
      },
      {
        name: "jus d'orange",
        quantity: 200,
        unit: "mL",
        photo: "",
      },
      {
        name: "miel",
        quantity: 1,
        unit: "c. à s.",
        photo: "",
      },
    ],
    steps: [
      "Lavez et équeutez les fraises.",
      "Placez les fraises, les framboises, les myrtilles, la banane coupée en morceaux et le jus d'orange dans un blender.",
      "Mixez jusqu'à obtenir une consistance lisse.",
      "Ajoutez le miel si désiré et mixez de nouveau.",
      "Versez dans des verres et servez immédiatement.",
    ],
    prepTiming: { duration: 10, unit: "min" },
    restTiming: { duration: 0, unit: "h" },
    cookTiming: { duration: 0, unit: "min" },
    photo:
      "https://previews.123rf.com/images/boarding1now/boarding1now1509/boarding1now150900010/45053380-smoothie-de-jus-de-fruits-milk-shake-aux-fruits-en-%C3%A9t%C3%A9-d-en-haut.jpg",
  },
  {
    name: "Mojito",
    id:3,
    category: "drinks",
    favorite: false,
    persons: 1,
    comments: [],
    ingredients: [
      {
        name: "citron vert",
        quantity: 0.5,
        unit: "",
        photo: "",
      },
      {
        name: "sucre de canne",
        quantity: 2,
        unit: "c. à c.",
        photo: "",
      },
      {
        name: "menthe",
        quantity: 6,
        unit: "feuilles",
        photo: "",
      },
      {
        name: "rhum blanc",
        quantity: 60,
        unit: "mL",
        photo: "",
      },
      {
        name: "eau gazeuse",
        quantity: 1,
        unit: "",
        photo: "",
      },
      {
        name: "glaçons",
        quantity: 1,
        unit: "",
        photo: "",
      },
    ],
    steps: [
      "Coupez le demi-citron vert en 4 morceaux.",
      "Placez les morceaux de citron vert dans un verre et ajoutez le sucre de canne.",
      "Pilez le citron et le sucre pour en extraire le jus.",
      "Ajoutez les feuilles de menthe et écrasez-les légèrement pour libérer leur arôme.",
      "Remplissez le verre de glaçons.",
      "Versez le rhum blanc et complétez avec de l'eau gazeuse.",
      "Mélangez doucement avec une cuillère.",
      "Décorez avec une branche de menthe et servez immédiatement.",
    ],
    prepTiming: { duration: 10, unit: "min" },
    restTiming: { duration: 0, unit: "h" },
    cookTiming: { duration: 0, unit: "min" },
    photo:
      "https://st.depositphotos.com/1364311/4658/i/450/depositphotos_46581171-stock-photo-mojito-cocktail.jpg",
  },
  {
    name: "Soupe à l'Oignon",
    id:4,
    category: "veg",
    favorite: false,
    persons: 4,
    comments: [],
    ingredients: [
      {
        name: "oignons",
        quantity: 500,
        unit: "g",
        photo: "",
      },
      {
        name: "bouillon de volaille",
        quantity: 1,
        unit: "L",
        photo: "",
      },
      {
        name: "beurre",
        quantity: 60,
        unit: "g",
        photo: "",
      },
      {
        name: "farine",
        quantity: 2,
        unit: "c. à s.",
        photo: "",
      },
      {
        name: "gruyère râpé",
        quantity: 100,
        unit: "g",
        photo: "",
      },
      {
        name: "pain",
        quantity: 4,
        unit: "tranches",
        photo: "",
      },
      {
        name: "sel",
        quantity: 1,
        unit: "",
        photo: "",
      },
      {
        name: "poivre",
        quantity: 1,
        unit: "",
        photo: "",
      },
    ],
    steps: [
      "Pelez et émincez les oignons.",
      "Faites fondre le beurre dans une grande casserole. Ajoutez les oignons et faites-les revenir à feu moyen jusqu'à ce qu'ils soient dorés.",
      "Saupoudrez de farine et mélangez bien. Laissez cuire 2 minutes en remuant.",
      "Versez le bouillon de volaille en remuant constamment. Portez à ébullition, puis baissez le feu et laissez mijoter 30 minutes. Salez et poivrez.",
      "Préchauffez le four en mode gril.",
      "Versez la soupe dans des bols résistants à la chaleur. Déposez une tranche de pain sur chaque bol, puis recouvrez de gruyère râpé.",
      "Passez les bols sous le gril du four jusqu'à ce que le fromage soit fondu et doré.",
      "Servez immédiatement.",
    ],
    prepTiming: { duration: 15, unit: "min" },
    restTiming: { duration: 0, unit: "h" },
    cookTiming: { duration: 45, unit: "min" },
    photo:
      "https://st2.depositphotos.com/1692343/6183/i/450/depositphotos_61830071-stock-photo-homemade-french-onion-soup.jpg",
  },
  {
    name: "Tarte aux Pommes",
    id:5,
    category: "desserts",
    favorite: false,
    persons: 8,
    comments: [],
    ingredients: [
      {
        name: "pâte feuilletée",
        quantity: 1,
        unit: "",
        photo: "",
      },
      {
        name: "pommes",
        quantity: 4,
        unit: "",
        photo: "",
      },
      {
        name: "sucre",
        quantity: 50,
        unit: "g",
        photo: "",
      },
      {
        name: "beurre",
        quantity: 50,
        unit: "g",
        photo: "",
      },
      {
        name: "sucre vanillé",
        quantity: 1,
        unit: "sachet",
        photo: "",
      },
    ],
    steps: [
      "Préchauffez le four à 180°C (thermostat 6).",
      "Étalez la pâte feuilletée dans un moule à tarte et piquez le fond avec une fourchette.",
      "Épluchez, épépinez et coupez les pommes en lamelles.",
      "Disposez les lamelles de pommes en rosace sur la pâte.",
      "Saupoudrez de sucre et de sucre vanillé. Répartissez des morceaux de beurre sur les pommes.",
      "Enfournez pendant 40 minutes.",
      "Servez tiède ou froid.",
    ],
    prepTiming: { duration: 20, unit: "min" },
    restTiming: { duration: 0, unit: "h" },
    cookTiming: { duration: 40, unit: "min" },
    photo:
      "https://assets.afcdn.com/story/20220307/2163587_w2121h2121c1cx1061cy707cxt0cyt0cxb2121cyb1414.jpg",
  },
  {
    name: "Salade César",
    id:6,
    category: "main-dishes",
    favorite: false,
    persons: 4,
    comments: [],
    ingredients: [
      {
        name: "cœurs de laitue romaine",
        quantity: 2,
        unit: "",
        photo: "",
      },
      {
        name: "filets de poulet",
        quantity: 2,
        unit: "",
        photo: "",
      },
      {
        name: "parmesan râpé",
        quantity: 50,
        unit: "g",
        photo: "",
      },
      {
        name: "pain de mie",
        quantity: 4,
        unit: "tranches",
        photo: "",
      },
      {
        name: "gousses d'ail",
        quantity: 2,
        unit: "",
        photo: "",
      },
      {
        name: "huile d'olive",
        quantity: 3,
        unit: "c. à s.",
        photo: "",
      },
      {
        name: "œuf",
        quantity: 1,
        unit: "",
        photo: "",
      },
      {
        name: "moutarde de Dijon",
        quantity: 1,
        unit: "c. à s.",
        photo: "",
      },
      {
        name: "vinaigre de vin blanc",
        quantity: 1,
        unit: "c. à s.",
        photo: "",
      },
      {
        name: "filets d'anchois",
        quantity: 2,
        unit: "",
        photo: "",
      },
      {
        name: "sel",
        quantity: 1,
        unit: "",
        photo: "",
      },
      {
        name: "poivre",
        quantity: 1,
        unit: "",
        photo: "",
      },
    ],
    steps: [
      "Lavez et essorez la laitue. Coupez les tranches de pain de mie en petits dés. Émincez l'ail.",
      "Dans une poêle, faites chauffer 2 cuillères à soupe d'huile d'olive. Faites revenir les dés de pain jusqu'à ce qu'ils soient dorés et croustillants. Égouttez sur du papier absorbant.",
      "Faites cuire les filets de poulet dans la poêle avec le reste d'huile d'olive jusqu'à ce qu'ils soient bien dorés. Coupez-les en lamelles.",
      "Dans un bol, mélangez l'œuf, la moutarde, le vinaigre, les anchois, le sel et le poivre. Mixez pour obtenir une sauce homogène.",
      "Dans un saladier, mélangez la laitue, les lamelles de poulet, les croûtons et le parmesan râpé.",
      "Versez la sauce par-dessus, mélangez bien et servez immédiatement.",
    ],
    prepTiming: { duration: 20, unit: "min" },
    restTiming: { duration: 0, unit: "h" },
    cookTiming: { duration: 10, unit: "min" },
    photo: "https://img.cuisineaz.com/680x357/2023/06/12/i194548-.jpg",
  },
  {
    name: "Ratatouille",
    id:7,
    category: "veg",
    favorite: false,
    persons: 4,
    comments: [],
    ingredients: [
      {
        name: "aubergine",
        quantity: 1,
        unit: "",
        photo: "",
      },
      {
        name: "courgette",
        quantity: 1,
        unit: "",
        photo: "",
      },
      {
        name: "poivron rouge",
        quantity: 1,
        unit: "",
        photo: "",
      },
      {
        name: "poivron vert",
        quantity: 1,
        unit: "",
        photo: "",
      },
      {
        name: "tomates",
        quantity: 4,
        unit: "",
        photo: "",
      },
      {
        name: "oignons",
        quantity: 2,
        unit: "",
        photo: "",
      },
      {
        name: "gousses d'ail",
        quantity: 2,
        unit: "",
        photo: "",
      },
      {
        name: "huile d'olive",
        quantity: 4,
        unit: "c. à s.",
        photo: "",
      },
      {
        name: "sel",
        quantity: 1,
        unit: "",
        photo: "",
      },
      {
        name: "poivre",
        quantity: 1,
        unit: "",
        photo: "",
      },
      {
        name: "thym",
        quantity: 1,
        unit: "",
        photo: "",
      },
      {
        name: "laurier",
        quantity: 1,
        unit: "",
        photo: "",
      },
    ],
    steps: [
      "Lavez et coupez l'aubergine, la courgette, les poivrons, et les tomates en dés.",
      "Pelez et émincez les oignons et l'ail.",
      "Dans une grande poêle, faites chauffer l'huile d'olive. Faites revenir les oignons et l'ail.",
      "Ajoutez les aubergines et les poivrons, laissez cuire 10 minutes en remuant régulièrement.",
      "Ajoutez les courgettes et les tomates, le sel, le poivre, le thym et le laurier. Mélangez bien.",
      "Couvrez et laissez mijoter à feu doux pendant 1 heure.",
      "Servez chaud ou froid.",
    ],
    prepTiming: { duration: 30, unit: "min" },
    restTiming: { duration: 0, unit: "h" },
    cookTiming: { duration: 1, unit: "h" },
    photo:
      "https://st2.depositphotos.com/3278179/9084/i/450/depositphotos_90841292-stock-photo-vegetable-ratatouille-baked-in-cast.jpg",
  },
  {
    name: "Tiramisu",
    id:8,
    category: "desserts",
    favorite: false,
    persons: 6,
    comments: [],
    ingredients: [
      {
        name: "cuisses de poulet",
        quantity: 4,
        unit: "",
        photo: "",
      },
      {
        name: "œufs",
        quantity: 3,
        unit: "",
        photo: "",
      },
      {
        name: "sucre",
        quantity: 100,
        unit: "g",
        photo: "",
      },
      {
        name: "mascarpone",
        quantity: 250,
        unit: "g",
        photo: "",
      },
      {
        name: "café fort",
        quantity: 50,
        unit: "g",
        photo: "",
      },
      {
        name: "liqueur (Amaretto, Marsala)",
        quantity: 2,
        unit: "c. à s.",
        photo: "",
      },
      {
        name: "biscuits à la cuillère",
        quantity: 24,
        unit: "mL",
        photo: "",
      },
      {
        name: "cacao en poudre",
        quantity: 1,
        unit: "",
        photo: "",
      },
    ],
    steps: [
      "Séparez les blancs des jaunes d'œufs. Fouettez les jaunes avec le sucre jusqu'à ce que le mélange blanchisse.",
      "Ajoutez le mascarpone et fouettez jusqu'à obtenir une crème lisse.",
      "Montez les blancs en neige ferme et incorporez-les délicatement à la crème de mascarpone.",
      "Mélangez le café refroidi avec la liqueur.",
      "Trempez rapidement les biscuits à la cuillère dans le café et disposez-les au fond d'un plat rectangulaire.",
      "Recouvrez d'une couche de crème au mascarpone. Répétez l'opération en alternant biscuits et crème, en terminant par une couche de crème.",
      "Réfrigérez au moins 4 heures.",
      "Avant de servir, saupoudrez de cacao en poudre.",
    ],
    prepTiming: { duration: 30, unit: "min" },
    restTiming: { duration: 0, unit: "h" },
    cookTiming: { duration: 4, unit: "h" },
    photo:
      "https://st2.depositphotos.com/1000336/9177/i/450/depositphotos_91774368-stock-photo-tiramisu-cake-with-mint-leaves.jpg",
  },
  {
    name: "Poulet basquaise",
    id:9,
    category: "main-dishes",
    favorite: false,
    persons: 6,
    comments: [],
    ingredients: [
      {
        name: "cuisses de poulet",
        quantity: 4,
        unit: "",
        photo: "",
      },
      {
        name: "poivrons",
        quantity: 4,
        unit: "",
        photo: "",
      },
      {
        name: "tomates",
        quantity: 4,
        unit: "",
        photo: "",
      },
      {
        name: "oignons",
        quantity: 2,
        unit: "",
        photo: "",
      },
      {
        name: "gousses d'ail",
        quantity: 3,
        unit: "",
        photo: "",
      },
      {
        name: "vin blanc sec",
        quantity: 200,
        unit: "mL",
        photo: "",
      },
      {
        name: "huile d'olive",
        quantity: 3,
        unit: "c. à s.",
        photo: "",
      },
      {
        name: "bouquet garni",
        quantity: 1,
        unit: "",
        photo: "",
      },
      {
        name: "sel",
        quantity: 1,
        unit: "",
        photo: "",
      },
      {
        name: "poivre",
        quantity: 1,
        unit: "",
        photo: "",
      },
    ],
    steps: [
      "Pelez et émincez les oignons et l'ail. Lavez, épépinez et coupez les poivrons en lanières. Pelez et concassez les tomates.",
      "Dans une cocotte, faites chauffer l'huile d'olive. Faites dorer les cuisses de poulet de tous les côtés. Retirez-les et réservez.",
      "Dans la même cocotte, faites revenir les oignons et l'ail. Ajoutez les poivrons et laissez cuire 10 minutes en remuant.",
      "Ajoutez les tomates, le bouquet garni, le sel et le poivre. Mélangez bien.",
      "Remettez les cuisses de poulet dans la cocotte, arrosez de vin blanc. Couvrez et laissez mijoter à feu doux pendant 1 heure.",
      "Servez chaud avec du riz ou des pommes de terre.",
    ],
    prepTiming: { duration: 20, unit: "min" },
    restTiming: { duration: 1, unit: "h" },
    cookTiming: { duration: 0, unit: "min" },
    photo:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRD24MzWvPGgyDbuappwEb8L0ehByZPTs6Iqg&s",
  },
  {
    name: "Quiche lorraine",
    id:10,
    category: "main-dishes",
    favorite: false,
    persons: 6,
    comments: [],
    ingredients: [
      {
        name: "pâte brisée",
        quantity: 1,
        unit: "",
        photo: "",
      },
      {
        name: "lardons fumés",
        quantity: 200,
        unit: "g",
        photo: "",
      },
      {
        name: "oeufs",
        quantity: 3,
        unit: "",
        photo: "",
      },
      {
        name: "crème fraîche",
        quantity: 200,
        unit: "mL",
        photo: "",
      },
      {
        name: "lait",
        quantity: 200,
        unit: "mL",
        photo: "",
      },
      {
        name: "fromage râpé",
        quantity: 100,
        unit: "g",
        photo: "",
      },
      {
        name: "poivre",
        quantity: 1,
        unit: "",
        photo: "",
      },
      {
        name: "sel",
        quantity: 1,
        unit: "",
        photo: "",
      },
      {
        name: "muscade",
        quantity: 1,
        unit: "",
        photo: "",
      },
    ],
    steps: [
      "Préchauffez le four à 180°C (thermostat 6).",
      "Étalez la pâte brisée dans un moule à tarte et piquez le fond avec une fourchette.",
      "Faites revenir les lardons dans une poêle sans ajouter de matière grasse. Égouttez-les sur du papier absorbant.",
      "Dans un saladier, battez les œufs, ajoutez la crème fraîche et le lait. Mélangez bien.",
      "Ajoutez le fromage râpé, les lardons, le sel, le poivre et la muscade. Mélangez de nouveau.",
      "Versez la préparation sur la pâte.",
      "Enfournez pendant 40 minutes.",
      "Laissez reposer 30 minutes avant de servir.",
    ],
    prepTiming: { duration: 20, unit: "min" },
    restTiming: { duration: 30, unit: "min" },
    cookTiming: { duration: 40, unit: "min" },
    photo:
      "https://st.depositphotos.com/1884173/4660/i/450/depositphotos_46606309-stock-photo-quiche-lorraine.jpg",
  },
  {
    name: "Fraisier",
    id:11,
    category: "desserts",
    favorite: false,
    persons: 6,
    comments: [
      {
        author: "Jean",
        note: 5,
        comment: "Cette recette a beaucoup plu à mes invités. A refaire.",
      },
      {
        author: "Marine",
        note: 5,
        comment: "Top !",
      },
      {
        author: "Jérémy",
        note: 1,
        comment: "Je préfère la recette des lasagnes.",
      },
    ],
    ingredients: [
      {
        name: "poivre",
        quantity: "",
        unit: "",
        photo: "https://assets.afcdn.com/recipe/20170607/67563_origin.jpg",
      },
      {
        name: "sel",
        quantity: "",
        unit: "",
        photo: "https://assets.afcdn.com/recipe/20170607/67687_origin.jpg",
      },
      {
        name: "beurre",
        quantity: 600,
        unit: "g",
        photo: "https://assets.afcdn.com/recipe/20201201/115998_origin.jpg",
      },
      {
        name: "vin rouge",
        quantity: 1,
        unit: "bouteille",
        photo: "https://assets.afcdn.com/recipe/20170607/67416_origin.jpg",
      },
      { name: "carottes", quantity: 4, unit: "", photo: "" },
      {
        name: "oignons",
        quantity: 4,
        unit: "",
        photo: "https://assets.afcdn.com/recipe/20170607/67621_origin.jpg",
      },
      { name: "boeuf", quantity: 600, unit: "g", photo: "" },
      {
        name: "bouquet garni",
        quantity: 1,
        unit: "",
        photo: "https://assets.afcdn.com/recipe/20170607/67407_origin.jpg",
      },
    ],
    steps: [
      "Détailler la viande en cubes de 3 cm de côté, enlever les gros morceaux de gras.",
      "Couper l'oignon en morceaux. Le faire revenir dans une poêle au beurre. Une fois transparent, le verser dans une cocotte en fonte de préférence.",
      "Procéder de même avec la viande mais en plusieurs fois, jusqu'à ce que tous les morceaux soient cuits. Les ajouter au fur et à mesure dans la cocotte. Ne pas avoir peur d'ajouter du beurre entre chaque fournée.",
      "Quand toute la viande est dans la cocotte, déglacer la poêle avec de l'eau ou du vin et faire bouillir en raclant pour récupérer le suc. Saler, poivrer, ajouter au reste.",
      "Recouvrir le tout avec une partie du vin et faire mijoter quelques heures avec le bouquet garni et les carottes en rondelles.",
      "Le lendemain, faire mijoter au moins 2 heures en plusieurs fois, ajouter du vin ou de l'eau si nécessaire.",
    ],
    prepTiming: { duration: 1, unit: "h" },
    restTiming: { duration: 0, unit: "min" },
    cookTiming: { duration: 4, unit: "h" },
    photo:
      "https://www.latelierderoxane.com/blog/wp-content/uploads/dsc0964-787x590.jpg",
  },
  {
    name: "Tomates Mozzarella",
    id:12,
    category: "veg",
    favorite: false,
    persons: 4,
    comments: [
      {
        author: "Jean",
        note: 2,
        comment: "Cette recette a beaucoup plu à mes invités. A refaire.",
      },
      {
        author: "Marine",
        note: 2,
        comment: "Top !",
      },
      {
        author: "Jérémy",
        note: 4,
        comment: "Je préfère la recette des lasagnes.",
      },
    ],
    ingredients: [
      {
        name: "poivre",
        quantity: "",
        unit: "",
        photo: "https://assets.afcdn.com/recipe/20170607/67563_origin.jpg",
      },
      {
        name: "sel",
        quantity: "",
        unit: "",
        photo: "https://assets.afcdn.com/recipe/20170607/67687_origin.jpg",
      },
      {
        name: "beurre",
        quantity: 600,
        unit: "g",
        photo: "https://assets.afcdn.com/recipe/20201201/115998_origin.jpg",
      },
      {
        name: "vin rouge",
        quantity: 1,
        unit: "bouteille",
        photo: "https://assets.afcdn.com/recipe/20170607/67416_origin.jpg",
      },
      { name: "carottes", quantity: 4, unit: "", photo: "" },
      {
        name: "oignons",
        quantity: 4,
        unit: "",
        photo: "https://assets.afcdn.com/recipe/20170607/67621_origin.jpg",
      },
      { name: "boeuf", quantity: 600, unit: "g", photo: "" },
      {
        name: "bouquet garni",
        quantity: 1,
        unit: "",
        photo: "https://assets.afcdn.com/recipe/20170607/67407_origin.jpg",
      },
    ],
    steps: [
      "Détailler la viande en cubes de 3 cm de côté, enlever les gros morceaux de gras.",
      "Couper l'oignon en morceaux. Le faire revenir dans une poêle au beurre. Une fois transparent, le verser dans une cocotte en fonte de préférence.",
      "Procéder de même avec la viande mais en plusieurs fois, jusqu'à ce que tous les morceaux soient cuits. Les ajouter au fur et à mesure dans la cocotte. Ne pas avoir peur d'ajouter du beurre entre chaque fournée.",
      "Quand toute la viande est dans la cocotte, déglacer la poêle avec de l'eau ou du vin et faire bouillir en raclant pour récupérer le suc. Saler, poivrer, ajouter au reste.",
      "Recouvrir le tout avec une partie du vin et faire mijoter quelques heures avec le bouquet garni et les carottes en rondelles.",
      "Le lendemain, faire mijoter au moins 2 heures en plusieurs fois, ajouter du vin ou de l'eau si nécessaire.",
    ],
    prepTiming: { duration: 1, unit: "h" },
    restTiming: { duration: 0, unit: "min" },
    cookTiming: { duration: 4, unit: "h" },
    photo:
      "https://st2.depositphotos.com/5518334/50824/i/450/depositphotos_508246842-stock-photo-classic-caprese-salad-mozzarella-cheese.jpg",
  },
  {
    name: "Boeuf bourguignon",
    id:13,
    category: "main-dishes",
    favorite: false,
    persons: 4,
    comments: [
      {
        author: "Jean",
        note: 5,
        comment: "Cette recette a beaucoup plu à mes invités. A refaire.",
      },
      {
        author: "Marine",
        note: 5,
        comment: "Top !",
      },
      {
        author: "Jérémy",
        note: 1,
        comment: "Je préfère la recette des lasagnes.",
      },
    ],
    ingredients: [
      {
        name: "poivre",
        quantity: "",
        unit: "",
        photo: "https://assets.afcdn.com/recipe/20170607/67563_origin.jpg",
      },
      {
        name: "sel",
        quantity: "",
        unit: "",
        photo: "https://assets.afcdn.com/recipe/20170607/67687_origin.jpg",
      },
      {
        name: "beurre",
        quantity: 600,
        unit: "g",
        photo: "https://assets.afcdn.com/recipe/20201201/115998_origin.jpg",
      },
      {
        name: "vin rouge",
        quantity: 1,
        unit: "bouteille",
        photo: "https://assets.afcdn.com/recipe/20170607/67416_origin.jpg",
      },
      { name: "carottes", quantity: 4, unit: "", photo: "" },
      {
        name: "oignons",
        quantity: 4,
        unit: "",
        photo: "https://assets.afcdn.com/recipe/20170607/67621_origin.jpg",
      },
      { name: "boeuf", quantity: 600, unit: "g", photo: "" },
      {
        name: "bouquet garni",
        quantity: 1,
        unit: "",
        photo: "https://assets.afcdn.com/recipe/20170607/67407_origin.jpg",
      },
    ],
    steps: [
      "Détailler la viande en cubes de 3 cm de côté, enlever les gros morceaux de gras.",
      "Couper l'oignon en morceaux. Le faire revenir dans une poêle au beurre. Une fois transparent, le verser dans une cocotte en fonte de préférence.",
      "Procéder de même avec la viande mais en plusieurs fois, jusqu'à ce que tous les morceaux soient cuits. Les ajouter au fur et à mesure dans la cocotte. Ne pas avoir peur d'ajouter du beurre entre chaque fournée.",
      "Quand toute la viande est dans la cocotte, déglacer la poêle avec de l'eau ou du vin et faire bouillir en raclant pour récupérer le suc. Saler, poivrer, ajouter au reste.",
      "Recouvrir le tout avec une partie du vin et faire mijoter quelques heures avec le bouquet garni et les carottes en rondelles.",
      "Le lendemain, faire mijoter au moins 2 heures en plusieurs fois, ajouter du vin ou de l'eau si nécessaire.",
    ],
    prepTiming: { duration: 1, unit: "h" },
    restTiming: { duration: 0, unit: "min" },
    cookTiming: { duration: 4, unit: "h" },
    photo: "https://assets.afcdn.com/recipe/20220707/133382_w600.jpg",
  },
  {
    name: "Gin Tonic",
    id:14,
    category: "drinks",
    favorite: false,
    persons: 4,
    comments: [
      {
        author: "Jean",
        note: 5,
        comment: "Cette recette a beaucoup plu à mes invités. A refaire.",
      },
      {
        author: "Marine",
        note: 5,
        comment: "Top !",
      },
      {
        author: "Jérémy",
        note: 1,
        comment: "Je préfère la recette des lasagnes.",
      },
    ],
    ingredients: [
      {
        name: "poivre",
        quantity: "",
        unit: "",
        photo: "https://assets.afcdn.com/recipe/20170607/67563_origin.jpg",
      },
      {
        name: "sel",
        quantity: "",
        unit: "",
        photo: "https://assets.afcdn.com/recipe/20170607/67687_origin.jpg",
      },
      {
        name: "beurre",
        quantity: 600,
        unit: "g",
        photo: "https://assets.afcdn.com/recipe/20201201/115998_origin.jpg",
      },
      {
        name: "vin rouge",
        quantity: 1,
        unit: "bouteille",
        photo: "https://assets.afcdn.com/recipe/20170607/67416_origin.jpg",
      },
      { name: "carottes", quantity: 4, unit: "", photo: "" },
      {
        name: "oignons",
        quantity: 4,
        unit: "",
        photo: "https://assets.afcdn.com/recipe/20170607/67621_origin.jpg",
      },
      { name: "boeuf", quantity: 600, unit: "g", photo: "" },
      {
        name: "bouquet garni",
        quantity: 1,
        unit: "",
        photo: "https://assets.afcdn.com/recipe/20170607/67407_origin.jpg",
      },
    ],
    steps: [
      "Détailler la viande en cubes de 3 cm de côté, enlever les gros morceaux de gras.",
      "Couper l'oignon en morceaux. Le faire revenir dans une poêle au beurre. Une fois transparent, le verser dans une cocotte en fonte de préférence.",
      "Procéder de même avec la viande mais en plusieurs fois, jusqu'à ce que tous les morceaux soient cuits. Les ajouter au fur et à mesure dans la cocotte. Ne pas avoir peur d'ajouter du beurre entre chaque fournée.",
      "Quand toute la viande est dans la cocotte, déglacer la poêle avec de l'eau ou du vin et faire bouillir en raclant pour récupérer le suc. Saler, poivrer, ajouter au reste.",
      "Recouvrir le tout avec une partie du vin et faire mijoter quelques heures avec le bouquet garni et les carottes en rondelles.",
      "Le lendemain, faire mijoter au moins 2 heures en plusieurs fois, ajouter du vin ou de l'eau si nécessaire.",
    ],
    prepTiming: { duration: 1, unit: "h" },
    restTiming: { duration: 0, unit: "min" },
    cookTiming: { duration: 4, unit: "h" },
    photo:
      "https://st4.depositphotos.com/1007248/24612/i/450/depositphotos_246122520-stock-photo-cocktail-gin-tonic-lemon-slices.jpg",
  },
];
